config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/board" => "homes#board"
  resources :votes
  resources :vote_answers, only: [:create]
  resources :public_relations
  resources :categories, except: [:show]
  resources :topics, except: [:index, :show]
  resources :users, except: [:new, :create, :destroy]
  # 掲示物作成画面での参加・不参加の変更時の処理
  patch '/user/change/:id' => 'users#change', as:'change_user'
  # 退会確認画面
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  # 退会の論理削除
  patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  resources :groups, except: [:new]
  # users/showから追加する場合
  post "/group_users/add_group" => "group_users#add_group", as: 'add_group'
  # groups/showから追加する場合
  post "/group_users/add_user" => "group_users#add_user", as: 'add_user'
  # groups/showから削除する場合
  delete "/group_users/:id/destroy_user" => "group_users#destroy_user", as: 'destroy_user'
  # users/showから削除する場合
  delete "/group_users/:id/destroy_group" => "group_users#destroy_group", as: 'destroy_group'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/public_relation.rb
class PublicRelation < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :topics, dependent: :destroy
end

app/controllers/public_relations_controller.rb
class PublicRelationsController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def new
    @public_relation = PublicRelation.new
    @category = Category.new
  end

  def create
    @public_relation = PublicRelation.new(public_relation_params)
    @public_relation.user_id = current_user.id
    if @public_relation.save
      session[:pr_memo_id] = @public_relation.id
      redirect_to public_relation_path(@public_relation.id)
    end
  end

  def index
    @groups = Group.all
    @public_relations = PublicRelation.all
    @key = params[:group_key].to_i
  end

  def show
    @public_relation = PublicRelation.find(params[:id])
    @users = User.all
    # 同じグループidのカテゴリーのみ
    @categories = Category.where(group_id: @public_relation.group.id)
    @topics = @public_relation.topics.all
  end

  def edit
  end

  def update
    @public_relation.update(public_relation_params)
    redirect_to public_relation_path(@public_relation.id)
  end

  def destroy
    @public_relation.destroy
    redirect_to public_relations_path
  end

  private

  def public_relation_params
    params.require(:public_relation).permit(:user_id, :group_id, :title, :topic, :body, :date)
  end

  def is_matching_login_user
    @public_relation = PublicRelation.find(params[:id])
    unless @public_relation.user_id == current_user.id
      flash[:public_relation_notice] = "広報資料の編集・削除は資料作成者のみ可能です"
      redirect_to public_relation_path(@public_relation.id)
    end
  end
end

app/helpers/public_relations_helper.rb
module PublicRelationsHelper
end

app/views/public_relations/_group.html.erb
  <% groups.each do |group| %>
    <li class="mb-1">
      <%= link_to group.name, group_path(group.id) %>
    </li>
  <% end %>

app/views/public_relations/edit.html.erb
<h1>広報資料編集</h1>

<%= form_with model: @public_relation do |f| %>
  <h4>理事会やイベントの開催日時</h4>
  <%= f.datetime_field :date %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>対象グループ</h4>
  <%= f.select :group_id, options_from_collection_for_select(Group.all, :id, :name) %>
  <%= f.submit "更新" %>
<% end %>

app/views/public_relations/index.html.erb
それぞれのグループの在籍者の確認ができます
<%= render 'group', groups: @groups %>
<%= link_to "グループ一覧", groups_path %>

<h1>掲示物一覧</h1>


<h3>確認したい掲示物のグループを選択してください</h3>
<%= link_to "すべて", public_relations_path(group_key: 0) %>
<% @groups.each do |group| %>
  <%= link_to group.name, public_relations_path(group_key: group.id) %>
<% end %>

<!--グループごとの表示に切り替える為のリンク-->
<% if @key == 0 %>
   <% @public_relations.each do |pr| %>
    <h3><%= pr.title %></h3>
    開催日時
    <%= format_time(pr.date) %>
    <%= link_to "詳細", public_relation_path(pr.id) %>
  <% end %>
<% elsif @key > 0 %>
  <% @groups.each do |group| %>
    <% group.public_relations.where(group_id: @key).each do |pr| %>
      <h3><%= pr.title %></h3>
      開催日時
      <%= format_time(pr.date) %>
      <%= link_to "詳細", public_relation_path(pr.id) %>
    <% end %>
  <% end %>
<% end %>

app/views/public_relations/new.html.erb
<h1>広報資料作成</h1>

<%= form_with model: @public_relation do |f| %>
  <h4>理事会やイベントの開催日時</h4>
  <%= f.datetime_field :date %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>対象グループ</h4>
  <%= f.select :group_id, options_from_collection_for_select(Group.all, :id, :name) %>
  <%= f.submit "次へ進む" %>
<% end %>

app/views/public_relations/show.html.erb
<h1>掲示物作成</h1>

<%= flash[:public_relation_notice] %>
<%= link_to "掲示物の削除", public_relation_path(@public_relation.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>

<div class="wrap">
  <ul id="tab-menu">
    <li><a href="#tab1" class="active">理事会議事録</a></li>
    <li><a href="#tab2">イベント掲示</a></li>
    <li><a href="#tab3">その他</a></li>
  </ul>
  <div id="tab-contents">

    <!--理事会議事録-->
    <div id="tab1" class="tab">
      <%= link_to "タイトル・日時の編集", edit_public_relation_path(@public_relation.id) %></br>
      <%= link_to "大項目を新しく作る", new_category_path %>
      <% @categories.each do |category| %>
        <h3>大項目：<%= category.name %></h3>
        <%= link_to "中項目と詳細内容の追加", new_topic_path(category_id: category.id, public_relation_id: @public_relation.id) %></br>
        <% if @topics.find_by(category_id: category.id) %>
          <% @topics.where(category_id: category.id).each do |topic| %>
            中項目：<%= topic.name %>
            <%= link_to "編集", edit_topic_path(topic.id) %>
            <%= link_to "削除", topic_path(topic.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
          <% end %>
        <% end %>
      <% end %>
      <h3>出席者編集（敬称略）</h3>
      <table>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.full_name %></td>
          <%= form_with model: user, url: change_user_path(user.id), method: :patch do |f| %>
          <td>
            <%= f.select :is_participated, options_for_select(User.is_participateds_i18n.invert, { :selected => user.is_participated }) %>
          </td>
          <%= hidden_field_tag :memo_id, @public_relation.id %>
          <td><%= f.submit "変更" %></td>
          <% end %>
        </tr>
        <% end %>
      </table>

      <!--掲示物としてのデザイン-->
      <h2><%= @public_relation.title %></h2>
      <strong>日時</strong><%= format_time(@public_relation.date) %></br>
      <strong>出席者（敬称略）</strong>
      <% count = 0%>
      <% @users.each do |user| %>
        <% unless user.is_participated == User.is_participateds.key(0) %>
          <%= user.full_name %> : <%= user.is_participated_i18n %>
        <% end %>
        <% count += 1 if user.is_participated == User.is_participateds.key(1) %></br>
      <% end %>
      出席者合計：<%= count %>名
      【議題】</br>

      <% @categories.each_with_index do |category, index_c| %>
        <%= index_c + 1 %>. <%= category.name %></br>
        <% if @topics.find_by(category_id: category.id) %>
          <% @topics.where(category_id: category.id).each_with_index do |topic, index_t| %>
            <li>
              （<%= index_t + 1 %>）<%= topic.name %>
              <%= topic.body %>
            </li>
          <% end %>
        <% else %>
          <li>
            なし
          </li>
        <% end %>
      <% end %>
    </div>

    <!--イベント掲示-->
    <div id="tab2" class="tab hide">
      <%= link_to "タイトル・日時の編集", edit_public_relation_path(@public_relation.id) %></br>
      <h3>大項目</h3>
      <% @categories.each do |category| %>
        <%= category.name %>
        <h3><%= link_to "中項目の追加", new_topic_path(category_id: category.id, public_relation_id: @public_relation.id) %></h3>
        <% if @topics.find_by(category_id: category.id) %>
          <% @topics.where(category_id: category.id).each do |topic| %>
            <%= topic.name %>
            <%= link_to "編集", edit_topic_path(topic.id) %>
            <%= link_to "削除", topic_path(topic.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
          <% end %>
        <% end %>
      <% end %>

      <!--掲示物としてのデザイン-->
      <h2><%= @public_relation.title %></h2>
      <strong>日時</strong><%= format_time(@public_relation.date) %></br>

      <% @categories.each do |category| %>
        <%= category.name %></br>
        <% if @topics.find_by(category_id: category.id) %>
          <% @topics.where(category_id: category.id).each do |topic| %>
            <li>
              <%= topic.name %></br>
              <%= topic.body %>
            </li>
          <% end %>
        <% else %>
          <li>
            なし
          </li>
        <% end %>
      <% end %>
    </div>

    <!--その他-->
    <div id="tab3" class="tab hide">
      その他
    </div>
  </div>
</div>