config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/board" => "homes#board"
  resources :votes
  resources :vote_answers, only: [:create]
  resources :public_relations
  resources :categories, except: [:show]
  resources :topics, except: [:index, :show]
  resources :users, except: [:new, :create, :destroy]
  # 掲示物作成画面での参加・不参加の変更時の処理
  patch '/user/change/:id' => 'users#change', as:'change_user'
  # 退会確認画面
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  # 退会の論理削除
  patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  resources :groups, except: [:new]
  # users/showから追加する場合
  post "/group_users/add_group" => "group_users#add_group", as: 'add_group'
  # groups/showから追加する場合
  post "/group_users/add_user" => "group_users#add_user", as: 'add_user'
  # groups/showから削除する場合
  delete "/group_users/:id/destroy_user" => "group_users#destroy_user", as: 'destroy_user'
  # users/showから削除する場合
  delete "/group_users/:id/destroy_group" => "group_users#destroy_group", as: 'destroy_group'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, through: :group_users
  has_many :group_users, dependent: :destroy
  accepts_nested_attributes_for :group_users
  has_many :public_relations # グループが削除されたら広報はグループ：その他へ移動させる為、dependent: :destroyはしない
  has_many :votes # グループが削除されたらアンケートはグループ：その他へ移動させる為、dependent: :destroyはしない
  has_many :categories # グループが削除されたらカテゴリーはグループ：その他へ移動させる為、dependent: :destroyはしない
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  # 新規作成は一覧画面に入っている
  def create
    @group = Group.new(group_params)
    @group.save
    redirect_to group_path(@group.id)
  end

  def index
    @group = Group.new
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @group_users =  @group.group_users.order(:user_id)
    @users_ary = []
    @users = User.all
    @users.each do |user|
      unless @group.group_users.find_by(user_id: user.id).present?
        @users_ary.push(user)
      end
    end
    @gourp_user = GroupUser.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to group_path(@group.id)
  end

  def destroy
    group = Group.find(params[:id])
    public_relations = PublicRelation.where(group_id: group.id)
    votes = Vote.where(group_id: group.id)
    categories = Category.where(group_id: group.id)
    group_other = Group.find_by(name: "その他")
    # 削除時に「グループ：その他」があれば、アソシエーション関係のあるモデルのgroup_idを「その他」のidに変更
    if group_other.present?
      public_relations.each do |pr|
        pr.update(group_id: group_other.id)
      end
      votes.each do |vote|
        vote.update(group_id: group_other.id)
      end
      categories.each do |category|
        category.update(group_id: group_other.id)
      end
    # 削除時に「グループ：その他」が無ければ作成し、アソシエーション関係のあるモデルのgroup_idを「その他」のidに変更
    else
      @group = Group.new
      @group.name = "その他"
      @group.save
      public_relations.each do |pr|
        pr.update(group_id: @group.id)
      end
      votes.each do |vote|
        vote.update(group_id: @group.id)
      end
      categories.each do |category|
        category.update(group_id: @group.id)
      end
    end
    group.destroy
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<h1>グループ名変更</h1>

<%= form_with model: @group do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "変更する" %>
<% end %>

app/views/groups/index.html.erb
<h1>グループ作成</h1>
<%= form_with model: @group, url: groups_path do |f| %>
  <%= f.text_field :name %>
  <%= f.hidden_field :memo1_id, :value => @group.id %>
  <%= f.submit "作成" %>
<% end %>

<h1>グループ一覧</h1>
※作成したグループを削除すると「その他グループ」が自動生成され、削除したグループに紐づく広報やアンケートは「その他グループ」に移動します。</br>
※「その他グループ」がある場合、「その他グループ」は削除できません。
<% unless @groups.empty? %>
  <% @groups.each do |group| %>
    <h2><%= group.name %></h2>
    参加人数：<%= group.group_users.size %>名
    <button><%= link_to "グループ参加者を確認する", group_path(group.id) %></button>
    <button><%= link_to "グループ名を変更する", edit_group_path(group.id) %></button>
    <% unless group.name == "その他" %>
      <button><%= link_to "グループを削除する", group_path(group.id), method: :delete, "data-confirm" => "本当に削除しますか？(このグループに属しているほかのアイテム（広報など）はグループ：その他へ移動します(グループ：その他が無い場合には生成します）" %></button>
    <% else %>
      （このグループは削除できません）
    <% end %>
    </br>
  <% end %>
<% else %>
    グループがありません
<% end %>

app/views/groups/show.html.erb
<h4>グループ：「<%= @group.name %>」の情報</h4>

<h5>参加者</h5>

<% if @group_users %>
  <% @group_users.each do |group_user| %>
    <%= group_user.user.full_name %>
    <% if group_user.user.is_deleted == true %>
      (理事退会済)
    <% end %>
    <%= link_to "グループ退会", destroy_user_path(group_user.id), method: :delete, "data-confirm" => "グループを退会しますか？" %>
  <% end %>
<% else %>
  参加している方はいません
<% end %>

<% if @users_ary.empty? %>
  <h5>全員参加中です</h5>
<% else %>
  <h5>グループへ追加する方を選択してください</h5>
  <% @users_ary.each do |user| %>
    <%= user.full_name %>
    <% if user.is_deleted == true %>
      (理事退会済)
    <% end %>
    <%= form_with model: @gourp_user, url: add_user_path, method: :post do |f| %>
      <%= f.hidden_field :group_id, :value => @group.id %>
      <%= f.hidden_field :user_id, :value => user.id %>
      <%= f.submit "参加" %>
    <% end %>
  <% end %>
<% end %>
<button><%= link_to "グループ名を変更する", edit_group_path(@group.id) %></button>
<% unless @group.name == "その他" %>
  <button><%= link_to "グループを削除する", group_path(@group.id), method: :delete, "data-confirm" => "本当に削除しますか？(このグループに属しているほかのアイテム（広報など）はグループ：その他へ移動します(グループ：その他が無い場合には生成します）" %></button>
<% else %>
  （このグループは削除できません）
<% end %>
<button><%= link_to "一覧へ戻る", groups_path %></button>