config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/board" => "homes#board"
  resources :votes
  resources :vote_answers, only: [:create]
  resources :public_relations
  resources :categories, except: [:show]
  resources :topics, except: [:index, :show]
  resources :users, except: [:new, :create, :destroy]
  # 掲示物作成画面での参加・不参加の変更時の処理
  patch '/user/change/:id' => 'users#change', as:'change_user'
  # 退会確認画面
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  # 退会の論理削除
  patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  resources :groups, except: [:new]
  # users/showから追加する場合
  post "/group_users/add_group" => "group_users#add_group", as: 'add_group'
  # groups/showから追加する場合
  post "/group_users/add_user" => "group_users#add_user", as: 'add_user'
  # groups/showから削除する場合
  delete "/group_users/:id/destroy_user" => "group_users#destroy_user", as: 'destroy_user'
  # users/showから削除する場合
  delete "/group_users/:id/destroy_group" => "group_users#destroy_group", as: 'destroy_group'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :votes # 理事が退会しても集計結果は残す為、dependent: :destroyはしない
  has_many :vote_answers # 理事が退会しても集計結果は残す為、dependent: :destroyはしない
  has_many :public_relations # 理事が変わっても広報は残す為、dependent: :destroyはしない
  has_many :groups, through: :group_users
  has_many :group_users, dependent: :destroy

  enum is_participated: {
    unselected: 0, # 未選択
    attendance: 1, # 出席
    absence: 2 # 欠席
  }

  def full_name
    self.last_name + " " + self.first_name
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update, :unsubscribe, :withdrawal]

  # 掲示物作成画面での参加・不参加の変更時の処理
  def change
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to public_relation_path(params[:memo_id])
  end

  def index
    @users = User.where(is_deleted: false)
    @deleted_users = User.where(is_deleted: true)
  end

  def show
    @user = User.find(params[:id])
    @group_users =  @user.group_users.order(:group_id)
    @groups_ary = []
    @groups = Group.all
    @groups.each do |group|
      unless @user.group_users.find_by(group_id: group.id).present?
        @groups_ary.push(group)
      end
    end
    @gourp_user = GroupUser.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.id == current_user.id
      @user.update(user_params)
    end
    redirect_to user_path(@user.id)
  end

  # 退会確認画面
  def unsubscribe
    @user = User.find(params[:id])
  end

  # 退会の論理削除
  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    flash[:withdrawal_notice] = "理事会を退会しました"
    redirect_to root_path
  end

  # def destroy
  #   user = User.find(params[:id])
  #   user.destroy
  #   reset_session
  #   redirect_to root_path
  # end

  private

  def user_params
    params.require(:user).permit(:email, :last_name, :first_name, :keyword, :is_participated)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      flash[:user_notice] = "理事情報の編集・退会処理は本人のみ可能です"
      redirect_to user_path(user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>理事情報 編集</h1>（敬称略）

<%= form_with model: @user do |f| %>
  <%= f.email_field :email %>
  <%= f.text_field :last_name %>
  <%= f.text_field :first_name %>
  <%= f.text_field :keyword %> ※理事長からの指示が無い限り変更しないでください
  <%= f.hidden_field :is_participated, :value => @user.is_participated %>
  <%= f.submit "変更する" %>
<% end %>

<button><%= link_to "理事登録状況へ戻る", user_path(@user.id) %></button>
<% if @user.is_deleted == false %>
  <button><%= link_to "理事会を退会する", unsubscribe_path(@user.id) %></button>
<% end %>
<button><%= link_to "理事一覧へ", users_path %></button>

app/views/users/index.html.erb
<h1>就任中の理事一覧</h1>（敬称略）

<% @users.each do |user| %>
  <%= user.full_name %>：
  <% if user.group_users.present? %>
    <% user.group_users.each_with_index do |g_user, index| %>
        <%= g_user.group.name %>
    <% end %>
  <% else %>
    参加しているグループはありません
  <% end %>
  <button><%= link_to "理事登録状況", user_path(user.id) %></button>
  <button><%= link_to "理事情報を編集する", edit_user_path(user.id) %></button>
  <button><%= link_to "理事会を退会する", unsubscribe_path(user.id) %></button></br>

<% end %>


<h1>退任済の理事一覧</h1>（敬称略）

<% @deleted_users.each do |user| %>
  <%= user.full_name %>：
  <% if user.group_users.present? %>
    参加中のグループ：
    <% user.group_users.each_with_index do |g_user, index| %>
        <%= g_user.group.name %>
    <% end %>
  <% else %>
    参加しているグループはありません
  <% end %>
  <button><%= link_to "理事登録状況", user_path(user.id) %></button>
  <button><%= link_to "理事情報を編集する", edit_user_path(user.id) %></button></br>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.full_name %>さんの情報</h1>
<%= flash[:user_notice] %>

<%= @user.email %>
<% if @user.is_deleted == false %>
  理事就任中
<% else %>
  理事退任済
<% end %>

<h5>参加しているグループ</h5>
<% unless @group_users.empty? %>
  <% @group_users.each do |group_user| %>
    <% unless @group_users.empty? %>
      <%= group_user.group.name %>
      <button><%= link_to "グループ退会", destroy_group_path(group_user.id), method: :delete, "data-confirm" => "グループを退会しますか？" %></button>
    <% end %>
  <% end %>
<% else %>
  参加しているグループがありません
<% end %>

<% if @groups.empty? %>
  <h5>グループが存在しません</h5>
<% else %>
  <% if @groups_ary.empty? %>
    <h5>全てのグループに参加中です</h5>
  <% else %>
    <h5>参加するグループを選択してください</h5>
    <% @groups_ary.each do |group| %>
      <%= group.name %>
      <%= form_with model: @gourp_user, url: add_group_path, method: :post do |f| %>
        <%= f.hidden_field :group_id, :value => group.id %>
        <%= f.hidden_field :user_id, :value => @user.id %>
        <%= f.submit "参加" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<button><%= link_to "理事情報を編集する", edit_user_path(@user.id) %></button>
<% if @user.is_deleted == false %>
  <button><%= link_to "理事会を退会する", unsubscribe_path(@user.id) %></button>
<% end %>
<button><%= link_to "理事一覧へ", users_path %></button>

app/views/users/unsubscribe.html.erb
<button><%= link_to "理事会を退会する", withdrawal_path(@user.id), method: :patch, "data-confirm" => "本当に退会しますか？" %></button>