config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/board" => "homes#board"
  resources :votes
  resources :vote_answers, only: [:create]
  resources :public_relations
  resources :categories, except: [:show]
  resources :topics, except: [:index, :show]
  resources :users, except: [:new, :create, :destroy]
  # 掲示物作成画面での参加・不参加の変更時の処理
  patch '/user/change/:id' => 'users#change', as:'change_user'
  # 退会確認画面
  get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  # 退会の論理削除
  patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  resources :groups, except: [:new]
  # users/showから追加する場合
  post "/group_users/add_group" => "group_users#add_group", as: 'add_group'
  # groups/showから追加する場合
  post "/group_users/add_user" => "group_users#add_user", as: 'add_user'
  # groups/showから削除する場合
  delete "/group_users/:id/destroy_user" => "group_users#destroy_user", as: 'destroy_user'
  # users/showから削除する場合
  delete "/group_users/:id/destroy_group" => "group_users#destroy_group", as: 'destroy_group'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :group
  has_many :vote_answers, dependent: :destroy

  validates :title, presence: true, length: {minimum: 2, maximum: 20}
  validates :question, presence: true, length: {minimum: 2, maximum: 200}
  validates :choice_1, presence: true, length: {minimum: 1, maximum: 50}
  validates :choice_2, presence: true, length: {minimum: 1, maximum: 50}
  validates :choice_3, presence: true, length: {minimum: 1, maximum: 50}
  validates :choice_4, presence: true, length: {minimum: 1, maximum: 50}

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def new
    @vote = Vote.new
  end

  def create
    @vote = Vote.new(vote_params)
    @vote.user_id = current_user.id
    if @vote.save
      redirect_to vote_path(@vote.id)
    else
      render :new
    end
  end

  def index
    @groups = Group.all
    @votes = Vote.all
  end

  def show
    @vote = Vote.find(params[:id])
    @user = current_user
    @vote_answer = VoteAnswer.new
    @user_vote_answer = @vote.vote_answers.find_by(vote_id: @vote.id, user_id: current_user.id)
    @answers = VoteAnswer.where(vote_id: @vote.id)
    # グラフ作成の為のカウント
    @answer_1 = 0
    @answer_2 = 0
    @answer_3 = 0
    @answer_4 = 0
    @answers.each do |ans|
      case ans.answer
      when @vote.choice_1
        @answer_1 += 1
      when @vote.choice_2
        @answer_2 += 1
      when @vote.choice_3
        @answer_3 += 1
      when @vote.choice_4
        @answer_4 += 1
      end
    end

  end

  def edit
    @vote = Vote.find(params[:id])
  end

  def update
    @vote = Vote.find(params[:id])
    @vote.update(vote_params)
    redirect_to vote_path(@vote.id)
  end

  def destroy
    vote = Vote.find(params[:id])
    vote.destroy
    redirect_to votes_path
  end

  private

  def vote_params
    params.require(:vote).permit(:user_id, :group_id, :title, :question, :choice_1, :choice_2, :choice_3, :choice_4)
  end

  def is_matching_login_user
    @vote = Vote.find(params[:id])
    unless @vote.user_id == current_user.id
      flash[:vote_notice] = "アンケートの編集・削除はアンケート作成者のみ可能です"
      redirect_to vote_path(@vote.id)
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/edit.html.erb
<h1>アンケート内容 編集</h1>

<% if @vote.errors.any? %>
  <%= @vote.errors.count %>件のエラーが発生しました
  <ul>
    <% @vote.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @vote do |f| %>
  <h4>タイトル（2～20文字）</h4>
  <%= f.text_area :title %>

  <h4>質問（2～200文字）</h4>
  <%= f.text_area :question %>
  <h4>選択肢（1～50文字）</h4>
  <%= f.text_field :choice_1 %>
  <%= f.text_field :choice_2 %>
  <%= f.text_field :choice_3 %>
  <%= f.text_field :choice_4 %>

  <h4>対象者</h4>
  <%= f.select :group_id, options_from_collection_for_select(Group.all, :id, :name) %>

  <%= f.submit "登録" %>
<% end %>

<button><%= link_to "詳細へ戻る", vote_path(@vote.id) %></button>
<button><%= link_to "アンケート一覧へ戻る", votes_path %></button>
<button><%= link_to "削除", vote_path(@vote.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></button>

app/views/votes/index.html.erb
グループ名変更
<%= render 'public_relations/group', groups: @groups %>

<h1>アンケート一覧</h1>


<% @votes.each do |vote| %>
  <%= vote.title %>
  対象グループ：
  <%= vote.group.name %>
  <button><%= link_to "詳細", vote_path(vote.id) %></button>
  <button><%= link_to "編集", edit_vote_path(vote.id) %></button>
  <button><%= link_to "削除", vote_path(vote.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></button>
<% end %>

app/views/votes/new.html.erb
<h1>新規 アンケート作成</h1>

<% if @vote.errors.any? %>
  <%= @vote.errors.count %>件のエラーが発生しました
  <ul>
    <% @vote.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @vote do |f| %>
  <h4>タイトル（2～20文字）</h4>
  <%= f.text_field :title %>

  <h4>質問（2～200文字）</h4>
  <%= f.text_area :question %>
  <h4>選択肢（1～50文字）</h4>
  <%= f.text_field :choice_1 %>
  <%= f.text_field :choice_2 %>
  <%= f.text_field :choice_3 %>
  <%= f.text_field :choice_4 %>

  <h4>対象者</h4>
  <%= f.select :group_id, options_from_collection_for_select(Group.all, :id, :name) %>

  <%= f.submit "登録" %>
<% end %>

app/views/votes/show.html.erb
<script>
  const answer_1 = <%= @answer_1 %>
  const answer_2 = <%= @answer_2 %>
  const answer_3 = <%= @answer_3 %>
  const answer_4 = <%= @answer_4 %>
</script>

<%= flash[:vote_notice] %>

<% if @user.vote_answers.find_by(vote_id: @vote.id) %>
  <h1>アンケートのご協力ありがとうございます。</h1>

  <h4>回答状況</h4>
  <p>回答済</p>
  <h4>タイトル</h4>
  <%= @vote.title %>

  <h4>対象グループ</h4>
  <%= @vote.group.name %>

  <h4>質問（2～200文字）</h4>
  <%= @vote.question %>
  <h4>選択肢（1～50文字）</h4>
  <%= @vote.choice_1 %></br>
  <%= @vote.choice_2 %></br>
  <%= @vote.choice_3 %></br>
  <%= @vote.choice_4 %>

  <h4><%= @user.last_name %>さんの回答</h4>
  <%= @user_vote_answer.answer %>

  <h4>現在の集計状況</h4>
  <table>
    <tr>
      <th class="total"><%= @vote.choice_1 %> :</th>
      <td class="total"><%= @answer_1 %></td>
      <td><div class="graph" id="graph_1"></div></td>
    </tr>
    <tr>
      <th class="total"><%= @vote.choice_2 %> :</th>
      <td class="total"><%= @answer_2 %></td>
      <td><div class="graph" id="graph_2"></div></td>
    </tr>
    <tr>
      <th class="total"><%= @vote.choice_3 %> :</th>
      <td class="total"><%= @answer_3 %></td>
      <td><div class="graph" id="graph_3"></div></td>
    </tr>
    <tr>
      <th class="total"><%= @vote.choice_4 %> :</th>
      <td class="total"><%= @answer_4 %></td>
      <td><div class="graph" id="graph_4"></div></td>
    </tr>
  </table>
  <script>
    graph_1.style.backgroundColor = "#33FFFF";
    graph_1.style.width = answer_1 * 20 + "px";
    graph_2.style.backgroundColor = "#33FFFF";
    graph_2.style.width = answer_2 * 20 + "px";
    graph_3.style.backgroundColor = "#33FFFF";
    graph_3.style.width = answer_3 * 20 + "px";
    graph_4.style.backgroundColor = "#33FFFF";
    graph_4.style.width = answer_4 * 20 + "px";
  </script>

<% elsif current_user.group_users.find_by(group_id: @vote.group_id) %>
  <h1>アンケートにご協力ください。</h1>

  <h4>回答状況</h4>
  <p>未回答</p>

  <%= flash[:vote_notice] %>

  <h4>タイトル</h4>
  <%= @vote.title %>

  <h4>対象グループ</h4>
  <%= @vote.group.name %>

  <h4>質問（2～200文字）</h4>
  <%= @vote.question %>
  <h4>選択肢（1～50文字）</h4>
  <%= form_with model: @vote_answer do |f| %>
    <%= f.radio_button :answer, @vote.choice_1 %>
    <%= f.label :answer, @vote.choice_1, value: @vote.choice_1 %></br>
    <%= f.radio_button :answer, @vote.choice_2 %>
    <%= f.label :answer, @vote.choice_2, value: @vote.choice_2 %></br>
    <%= f.radio_button :answer, @vote.choice_3 %>
    <%= f.label :answer, @vote.choice_3, value: @vote.choice_3 %></br>
    <%= f.radio_button :answer, @vote.choice_4 %>
    <%= f.label :answer, @vote.choice_4, value: @vote.choice_4 %>
    <%= f.hidden_field :vote_id, :value => @vote.id %>
    <%= f.submit "回答する" %>
  <% end %>
  <a href="javascript:onClick()">現在の集計状況を見る</a>
  <table id="table">
    <tr>
      <th class="total"><%= @vote.choice_1 %> :</th>
      <td class="total"><%= @answer_1 %></td>
      <td><div class="graph" id="graph_1"></div></td>
    </tr>
    <tr>
      <th class="total"><%= @vote.choice_2 %> :</th>
      <td class="total"><%= @answer_2 %></td>
      <td><div class="graph" id="graph_2"></div></td>
    </tr>
    <tr>
      <th class="total"><%= @vote.choice_3 %> :</th>
      <td class="total"><%= @answer_3 %></td>
      <td><div class="graph" id="graph_3"></div></td>
    </tr>
    <tr>
      <th class="total"><%= @vote.choice_4 %> :</th>
      <td class="total"><%= @answer_4 %></td>
      <td><div class="graph" id="graph_4"></div></td>
    </tr>
  </table>
  <script>
    function onClick() {
      table.style.visibility = "visible";
      graph_1.style.backgroundColor = "#33FFFF";
      graph_1.style.width = answer_1 * 20 + "px";
      graph_2.style.backgroundColor = "#33FFFF";
      graph_2.style.width = answer_2 * 20 + "px";
      graph_3.style.backgroundColor = "#33FFFF";
      graph_3.style.width = answer_3 * 20 + "px";
      graph_4.style.backgroundColor = "#33FFFF";
      graph_4.style.width = answer_4 * 20 + "px";
    }
  </script>
<% else %>
  このアンケートは「<%= @vote.group.name %>」参加者のみ対象です
<% end %>

<button><%= link_to "アンケート一覧へ", votes_path %></button>
<button><%= link_to "編集", edit_vote_path(@vote.id) %></button>
<button><%= link_to "削除", vote_path(@vote.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></button>